{{- if .Values.listeners.enabled }}
# templates/listeners/listener-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gwtm.fullname" . }}-listener-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "gwtm.labels" . | nindent 4 }}
type: Opaque
data:
  # Kafka credentials
  kafka-client-id: {{ .Values.listeners.kafka.clientId | b64enc | quote }}
  kafka-client-secret: {{ .Values.listeners.kafka.clientSecret | b64enc | quote }}

  # GWTM API token
  api-token: {{ .Values.listeners.api.token | b64enc | quote }}

  {{- if eq .Values.listeners.storage.type "s3" }}
  # AWS S3 credentials
  aws-access-key-id: {{ .Values.listeners.storage.s3.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.listeners.storage.s3.secretAccessKey | b64enc | quote }}
  {{- end }}

  {{- if eq .Values.listeners.storage.type "swift" }}
  # OpenStack Swift credentials
  swift-username: {{ .Values.listeners.storage.swift.username | b64enc | quote }}
  swift-password: {{ .Values.listeners.storage.swift.password | b64enc | quote }}
  {{- end }}
{{- end }}
