apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: gwtm
build:
  artifacts:
    - image: gwtm
      context: ..
      docker: {}
    - image: gwtm-fastapi
      context: ..
      docker:
        dockerfile: server/Dockerfile
  local:
    push: false
manifests:
  helm:
    releases:
      - name: gwtm
        chartPath: .
        valuesFiles:
          - values-dev.yaml
        setValues:
          backend.image.repository: gwtm
          backend.image.tag: latest
          backend.livenessProbe.enabled: "true"
          backend.readinessProbe.enabled: "true"
          cache.livenessProbe.enabled: "true"
          cache.persistence.enabled: "false"
          cache.readinessProbe.enabled: "true"
          database.initScripts.enabled: "true"
          database.livenessProbe.enabled: "true"
          database.persistence.enabled: "false"
          database.readinessProbe.enabled: "true"
          global.createNamespace: "true"
          global.namespace: gwtm
        createNamespace: true
        wait: true
        upgradeOnChange: true
deploy:
  helm:
    releases:
      - name: gwtm
        chartPath: .
        valuesFiles:
          - values-dev.yaml
        setValues:
          backend.image.repository: gwtm
          backend.image.tag: latest
          backend.livenessProbe.enabled: "true"
          backend.readinessProbe.enabled: "true"
          cache.livenessProbe.enabled: "true"
          cache.persistence.enabled: "false"
          cache.readinessProbe.enabled: "true"
          database.initScripts.enabled: "true"
          database.livenessProbe.enabled: "true"
          database.persistence.enabled: "false"
          database.readinessProbe.enabled: "true"
          global.createNamespace: "true"
          global.namespace: gwtm
        createNamespace: true
        wait: true
        upgradeOnChange: true
portForward:
  - resourceType: service
    resourceName: flask-backend
    namespace: gwtm
    port: 8080
    address: 0.0.0.0
    localPort: 8080
  - resourceType: service
    resourceName: frontend
    namespace: gwtm
    port: 80
    address: 0.0.0.0
    localPort: 8081
  - resourceType: service
    resourceName: fastapi-backend
    namespace: gwtm
    port: 8000
    address: 0.0.0.0
    localPort: 8000
