apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: gwtm
build:
  artifacts:
    - image: gwtm
      context: ..
      docker: {}
    - image: gwtm-fastapi
      context: ..
      docker:
        dockerfile: server/Dockerfile
      sync:
        manual:
          - src: "server/routes/**/*.py"
            dest: "/app/server/routes/"
          - src: "server/db/**/*.py"
            dest: "/app/server/db/"
          - src: "server/schemas/**/*.py"
            dest: "/app/server/schemas/"
          - src: "server/services/**/*.py"
            dest: "/app/server/services/"
          - src: "server/utils/**/*.py"
            dest: "/app/server/utils/"
          - src: "server/auth/**/*.py"
            dest: "/app/server/auth/"
          - src: "server/core/**/*.py"
            dest: "/app/server/core/"
          - src: "server/main.py"
            dest: "/app/server/"
          - src: "server/config.py"
            dest: "/app/server/"
    - image: gwtm-frontend
      context: ../frontend
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app/src/"
          - src: "*.js"
            dest: "/app/"
          - src: "*.ts"
            dest: "/app/"
          - src: "*.json"
            dest: "/app/"
  local:
    push: false
manifests:
  helm:
    releases:
      - name: gwtm
        chartPath: .
        valuesFiles:
          - values-dev.yaml
          - values-secrets.yaml
        setValues:
          backend.image.repository: gwtm
          backend.image.tag: latest
          backend.livenessProbe.enabled: "true"
          backend.readinessProbe.enabled: "true"
          database.initScripts.enabled: "true"
          database.livenessProbe.enabled: "true"
          database.persistence.enabled: "false"
          database.readinessProbe.enabled: "true"
          fastapi.image.repository: gwtm-fastapi
          fastapi.image.tag: latest
          frontend.image.repository: gwtm-frontend
          frontend.image.tag: latest
          global.createNamespace: "true"
          global.namespace: gwtm
          global.useGeneratedSecrets: "true"
        createNamespace: true
        wait: true
        upgradeOnChange: true
deploy:
  helm:
    releases:
      - name: gwtm
        chartPath: .
        valuesFiles:
          - values-dev.yaml
          - values-secrets.yaml
        setValues:
          backend.image.repository: gwtm
          backend.image.tag: latest
          backend.livenessProbe.enabled: "true"
          backend.readinessProbe.enabled: "true"
          database.initScripts.enabled: "true"
          database.livenessProbe.enabled: "true"
          database.persistence.enabled: "false"
          database.readinessProbe.enabled: "true"
          fastapi.image.repository: gwtm-fastapi
          fastapi.image.tag: latest
          frontend.image.repository: gwtm-frontend
          frontend.image.tag: latest
          global.createNamespace: "true"
          global.namespace: gwtm
          global.useGeneratedSecrets: "true"
        createNamespace: true
        wait: true
        upgradeOnChange: true
portForward:
  - resourceType: service
    resourceName: flask-backend
    namespace: gwtm
    port: 8080
    address: 0.0.0.0
    localPort: 8080
  - resourceType: service
    resourceName: frontend
    namespace: gwtm
    port: 3000
    address: 0.0.0.0
    localPort: 3000
  - resourceType: service
    resourceName: fastapi-backend
    namespace: gwtm
    port: 8000
    address: 0.0.0.0
    localPort: 8000
