# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "gwtm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.dbUser }}
  db-user: {{ .Values.secrets.dbUser | b64enc | quote }}
  {{- else }}
  db-user: {{ "postgres" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.dbPassword }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.dbName }}
  db-name: {{ .Values.secrets.dbName | b64enc | quote }}
  {{- else }}
  db-name: {{ "treasuremap" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.mailPassword }}
  mail-password: {{ .Values.secrets.mailPassword | b64enc | quote }}
  {{- else }}
  mail-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.awsAccessKeyId }}
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  {{- else }}
  aws-access-key-id: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.awsSecretAccessKey }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
  {{- else }}
  aws-secret-access-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.recaptchaPublicKey }}
  recaptcha-public-key: {{ .Values.secrets.recaptchaPublicKey | b64enc | quote }}
  {{- else }}
  recaptcha-public-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.recaptchaPrivateKey }}
  recaptcha-private-key: {{ .Values.secrets.recaptchaPrivateKey | b64enc | quote }}
  {{- else }}
  recaptcha-private-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.zenodoAccessKey }}
  zenodo-access-key: {{ .Values.secrets.zenodoAccessKey | b64enc | quote }}
  {{- else }}
  zenodo-access-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.extraSecrets }}
  {{- range $key, $value := .Values.secrets.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
