# templates/secrets.yaml
{{- if .Values.global.useGeneratedSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "gwtm.labels" . | nindent 4 }}
type: Opaque
data:
  # Database configuration
  {{- if .Values.secrets.dbUser }}
  db-user: {{ .Values.secrets.dbUser | b64enc | quote }}
  {{- else }}
  db-user: {{ "postgres" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.dbPassword }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.dbName }}
  db-name: {{ .Values.secrets.dbName | b64enc | quote }}
  {{- else }}
  db-name: {{ "treasuremap" | b64enc | quote }}
  {{- end }}
  
  # Mail configuration
  {{- if .Values.secrets.mailPassword }}
  mail-password: {{ .Values.secrets.mailPassword | b64enc | quote }}
  {{- else }}
  mail-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.mailUsername }}
  MAIL_USERNAME: {{ .Values.secrets.mailUsername | b64enc | quote }}
  {{- else }}
  MAIL_USERNAME: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.mailDefaultSender }}
  MAIL_DEFAULT_SENDER: {{ .Values.secrets.mailDefaultSender | b64enc | quote }}
  {{- else }}
  MAIL_DEFAULT_SENDER: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.mailServer }}
  MAIL_SERVER: {{ .Values.secrets.mailServer | b64enc | quote }}
  {{- else }}
  MAIL_SERVER: {{ "smtp.gmail.com" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.mailPort }}
  MAIL_PORT: {{ .Values.secrets.mailPort | b64enc | quote }}
  {{- else }}
  MAIL_PORT: {{ "465" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.admins }}
  ADMINS: {{ .Values.secrets.admins | b64enc | quote }}
  {{- else }}
  ADMINS: {{ "" | b64enc | quote }}
  {{- end }}
  
  # AWS configuration
  {{- if .Values.secrets.awsAccessKeyId }}
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  {{- else }}
  aws-access-key-id: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.awsSecretAccessKey }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
  {{- else }}
  aws-secret-access-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.awsDefaultRegion }}
  AWS_DEFAULT_REGION: {{ .Values.secrets.awsDefaultRegion | b64enc | quote }}
  {{- else }}
  AWS_DEFAULT_REGION: {{ "us-east-2" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.awsBucket }}
  AWS_BUCKET: {{ .Values.secrets.awsBucket | b64enc | quote }}
  {{- else }}
  AWS_BUCKET: {{ "gwtreasuremap" | b64enc | quote }}
  {{- end }}
  
  # Azure configuration
  {{- if .Values.secrets.azureAccountName }}
  AZURE_ACCOUNT_NAME: {{ .Values.secrets.azureAccountName | b64enc | quote }}
  {{- else }}
  AZURE_ACCOUNT_NAME: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.azureAccountKey }}
  AZURE_ACCOUNT_KEY: {{ .Values.secrets.azureAccountKey | b64enc | quote }}
  {{- else }}
  AZURE_ACCOUNT_KEY: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.storageBucketSource }}
  STORAGE_BUCKET_SOURCE: {{ .Values.secrets.storageBucketSource | b64enc | quote }}
  {{- else }}
  STORAGE_BUCKET_SOURCE: {{ "s3" | b64enc | quote }}
  {{- end }}
  
  # reCAPTCHA configuration
  {{- if .Values.secrets.recaptchaPublicKey }}
  recaptcha-public-key: {{ .Values.secrets.recaptchaPublicKey | b64enc | quote }}
  {{- else }}
  recaptcha-public-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.recaptchaPrivateKey }}
  recaptcha-private-key: {{ .Values.secrets.recaptchaPrivateKey | b64enc | quote }}
  {{- else }}
  recaptcha-private-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  # Zenodo configuration
  {{- if .Values.secrets.zenodoAccessKey }}
  zenodo-access-key: {{ .Values.secrets.zenodoAccessKey | b64enc | quote }}
  {{- else }}
  zenodo-access-key: {{ "" | b64enc | quote }}
  {{- end }}
  
  # Additional secrets
  {{- if .Values.secrets.extraSecrets }}
  {{- range $key, $value := .Values.secrets.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}